### ISSUE TITLE
Service Reload Duplicate Declaration

### ISSUE THREAD

**Issue by discreet** [pcfens/puppet-yas3fs#4]
In the yas3fs::mount define the reload of the service has a static namevar which causes a duplicate declaration error when you have multiple resources declared. This should be made to be dynamic like the rest of the resources in the define.

https://github.com/pcfens/puppet-yas3fs/blob/master/manifests/mount.pp#L43-L52

If I have the free time, I'll submit the PR in the next few days.

**Comment by pcfens** [comment]
Thanks. I pushed a fix up to the forge as v0.3.3.
